name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install EF Core CLI
      run: dotnet tool install --global dotnet-ef --version 6.0.26
      shell: bash

    - name: Update database
      run: |
        cd PrincipalEFCoreMVC/Migrations
        dotnet ef database update 20240126190908_Initial
